### ISSUE TITLE
workflow: add kubernetes_memory_limit

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-atlas-recast#32]
Enrich example with `kubernetes_memory_limit` directive in order to be able to run the workflow with as little memory consumption as possible.  This means:

1. Run the workflow as is now, and observe real memory usage via `kubectl top pods` or via logging into the node and using `top` for each job. For example, 2GiB can be consumed for one step.

2. Amend workflow definition to introduce `kubernetes_memory_limit` for each step and use value observed above.

3. Run example successfully on REANA and lower the value in order to have them as low as possible for each step.

This will allow ultimately to run many ATLAS RECAST demo workflows in parallel.

**Comment by VMois** [comment]
the memory limit of:

- `1MiB` for this demo triggers a memory limit error;
- `4MiB` took around 10 minutes to finish;
- `32MiB` took around 1.5 minutes;
- `64MiB` took around 50 seconds;

I will put `128MiB` to be on the safe side (the number is still very small).
