### ISSUE TITLE
Make a 'main' branch

### ISSUE THREAD

**Issue by matthewfeickert** [reanahub/reana-demo-atlas-recast#43]
@tiborsimko or @lukasheinrich  Can I get you to do me a favor and just do the following to get a `main` branch to exist (not even be the default)?

```
git checkout origin/master -b main && git push -u origin HEAD
```

The reason I want this is because in https://github.com/yadage/yadage-schemas/pull/44/files the value of the default target branch in `generic_github_url` got changed from `master` to `main`. This went into [`yadage-schemas` `v0.11.0`](https://github.com/yadage/yadage-schemas/releases/tag/v0.11.0) which is now getting picked up in `recast-atlas` causing things like https://gitlab.cern.ch/recast-atlas/examples/public-examples-tests/-/merge_requests/4 to fail because [`examples/rome`](https://github.com/recast-hep/recast-atlas/blob/de61902bc6a66104965cced12471a8f195075bb3/src/recastatlas/data/catalogue/examples_rome.yml) is picking up 

```yaml
spec:
  toplevel: github:reanahub/reana-demo-atlas-recast
  workflow: workflow/workflow.yml
```

and https://github.com/reanahub/reana-demo-atlas-recast/ doens't have a `main` branch for it to get targeted in the `github:<username/repo[@branch]>[:subpath]` `toplevel` format.

I'm going to fix this in https://github.com/recast-hep/recast-atlas but it would be good to have this get fixed everywhere that has something like this copied as well.

**Comment by tiborsimko** [comment]
Hi @matthewfeickert The `main` branch has been created. (We'll keep the `master` branch as well due to the rest of the REANA repository ecosystem.)

**Comment by matthewfeickert** [comment]
> We'll keep the master branch as well due to the rest of the REANA repository ecosystem.)

Excellent! I was going to ask for this anyway to ensure older releases didn't break. Thanks @tiborsimko!
